#!/bin/sh
#
# git "pre-commit" hook.

bold=`tput bold`
blink=`tput blink`
orange=`tput setab 202`
green=`tput setab 2`
reset=`tput sgr0`

echo "Running PHPCS test before commit...\n"

composer php-unit-test-automation

filename=".phpcs-log.txt"

if [ -f ${filename} ]
then
	error=`grep "ERROR" ${filename}`
	
	if [ ! -z "$error" ]
	then
		echo "\n${orange}${bold}Error Found...${reset} ${bold}Please fix those before commit.${reset}\n"
		composer php-unit-test
		exit 1
	else
		echo "${green}Test Status: OK, commiting...${reset}"
	fi
fi

