#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

bold=`tput bold`
blink=`tput blink`
orange=`tput setab 202`
green=`tput setab 2`
reset=`tput sgr0`

echo "Running PHPCS test before commit...\n"

composer pcs

filename=".phpcs-log.txt"

if [ -f ${filename} ]
then
	error=`grep "ERROR" ${filename}`
	
	if [ ! -z "$error" ]
	then
		echo "\n${orange}${bold}Error Found...${reset} ${bold}Please fix those before commit.${reset}\n"
		composer cs
		exit 1
	else
		echo "${green}Test Status: OK, commiting...${reset}"
	fi
fi

